


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {

            display: flex;
            justify-content: center;
            align-items: center;
            background-color: rgba(0,0,0,0.1);
        }

        .container {
            position: absolute;
            width: 800px;
            height: 100%;
            margin: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #fff;
            top:5px
        }

        .recp {
            height: 100%;
            width: 70%;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            background-color: #333;
            padding-bottom:20px;
            box-shadow: 0 5px 5px rgba(0,0,0,0.8);
            border-radius: 2px;


        }

      table{
          height: 100%;
          width: 100%;
          border-collapse: collapse;
      }

      .bold{
          font-weight: 500;
          font-size: 1.2rem;
      }
      .height{
          height: 100px;
      }
      .back{
          background: rgba(255,255,255,0.2);
          border-color: rgba(255,255,255,0.2);
      }
      .right{
          text-align: center;

      }
      .pad{
          padding-left: 10px;
      }




        @media screen and (max-width:991px){
            .container{
                width: 100%;
            }
            .recp{
                width: 90%;

            }

        }
    </style>

</head>

<body>
    <div class="container">
        <div class="recp">
            <table>
                <tr class="back">
                    <td class="bold  back" style="text-align: center;">Payment Method</td>
                    <td class="bold back" style="text-align: center;">Online Transaction</td>
                </tr>

                <tr>
                    <td class="pad">Name</td>
                    <td class="right">{{$data->user->name}}</td>

                </tr>
                <tr>
                    <td class="height pad ">Address</td>
                    <td class="height right">{{$data->address}}</td>

                </tr>
                <tr>
                    <td class="pad">Mobile number</td>
                    <td class="right">{{$data->mobile}}</td>

                </tr>
                @foreach ($data->product as $user)
                <tr>
                    <td class="bold  back pad">Product</td>
                    <td class="bold  back right">Price</td>

                </tr>
                <tr>
                    <td class="pad">{{ $user['name'] }}</td>
                    <td class="right">{{ $user['price'] }}</td>

                </tr>
@endforeach

                <tr>
                    <td style="border-top: 1px solid #fff;border-bottom: 1px solid #fff; font-weight: bold;  " class="pad">Grand Total</td>
                    <td style="border-top: 1px solid #fff;border-bottom: 1px solid #fff; font-weight: bold;"class="right"> {{$data->total}}</td>
                </tr>
                <tr>
                    <td></td>

                    <td>

                        <form action="{{route('razo')}}" method="POST">
                            <input type="hidden" name="oder_id" value="{{$data->id}}">


                            <script     src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_IHMVXVPgvdVv7Q"
                            Enter the Test API Key ID generated from Dashboard → Settings → API Keys    data-amount="{{$data->total*100}}"
                            Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                               data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                               //Replace with the order_id generated by you in the backend.

                                   data-name="Gym"    data-description="Payment"  data-prefill.contact="{{Auth()->user()->mobile}}"     data-prefill.contact="{{$data->mobile}}"
                                      data-image=""    data-prefill.name=""    data-prefill.email="{{ Auth()->user()->email }}"
                                        data-theme.color="#363945" ></script><input type="hidden" custom="Hidden Element" name="hidden" id="" >

                                    </form>

                    </td>
                </tr>


            </table>


        </div>
    </div>

</body>

</html>
